project_id = "zbeiifflalqondrwdmkp"

[functions.generate-taxonomy]
verify_jwt = false

[functions.create-ticket]
verify_jwt = false

[functions.push-taxonomy-to-amplitude]
verify_jwt = false

[functions.events-config]
verify_jwt = false